import test from "node:test";
import assert from "node:assert/strict";
import { RESEARCH_BRAIN_CONTRACT_VERSION } from "../lib/dossier-v2/research-brain-contracts.ts";
import { validateResearchBrainOutput } from "../lib/dossier-v2/research-brain-validation.ts";
import { runResearchBrain } from "../lib/dossier-v2/research-brain.ts";

const packet: any = { packet_id: "packet-1", contract_version: "dossier-v2-input/1", as_of: "2026-09-18T00:00:00.000Z", previous_dossier_id: null, observed_evidence: [{ evidence_id: "e1", epistemic_label: "OBSERVED", claim_or_fact: "Front-end yields rose.", category: "MARKET_DATA", source_type: "MARKET_DATA", available_at: "2026-09-18T00:00:00.000Z", provenance: [] }], research_leads: [{ lead_id: "l1", claim_or_question: "Verify duration positioning.", source_type: "LEAD", available_at: "2026-09-18T00:00:00.000Z", provenance: [] }], prior_analytical_state: { previous_dossier_id: null, as_of: null, prior_claims: [], thesis_ledger: null }, development_clusters: [], creator_themes: [], catalysts: [], thesis_ledger: null, freshness_warnings: [], research_gaps: [], diagnostics: {} };
const input: any = { contract_version: RESEARCH_BRAIN_CONTRACT_VERSION, packet };
function degradedShape() { return { contract_version: RESEARCH_BRAIN_CONTRACT_VERSION, packet_id: "packet-1", as_of: packet.as_of, main_thread: { thread_id: "t", headline: "x", answer: "x", regime_implication: "x", epistemic_label: "SPECULATIVE", evidence_refs: [], supporting_story_ids: [], contradiction_refs: [], what_would_change_mind: "x" }, major_stories: [], investigations: [], chart_investigation_queue: { core: [], optional: [] }, market_verdict: { summary: "x", lenses: [], cross_asset_readthrough: [], overall_confidence: "SPECULATIVE", dominant_confirmation: null, dominant_contradiction: null }, research_now: [], scheduled_catalysts: [], thesis_tripwires: [], investigation_triggers: [], stock_radar: [], developing_themes: [], creator_theme_expansions: [], thesis_ledger: { contract_version: "thesis-ledger/2", entries: [] }, unresolved_contradictions: [], diagnostics: { degraded: true, degradation_reasons: [], omitted_or_demoted_items: [], missing_input_categories: [], model_repair_used: false } }; }
test("Research Brain rejects unsupported evidence IDs", () => { const output = degradedShape(); output.main_thread.evidence_refs = [{ kind: "observed_evidence", id: "missing" }]; assert.equal(validateResearchBrainOutput(output, input).valid, false); });
test("Research Brain rejects prior-only OBSERVED claims", () => { const output = degradedShape(); output.main_thread.epistemic_label = "OBSERVED"; output.main_thread.evidence_refs = [{ kind: "prior_claim", id: "prior" }]; assert.equal(validateResearchBrainOutput(output, input).valid, false); });
test("Research Brain performs one repair retry and then degrades", async () => { let calls = 0; const result = await runResearchBrain(input, async () => { calls++; return { data: {}, requestId: null, responseId: null, model: "test", inputTokens: null, outputTokens: null, totalTokens: null }; }); assert.equal(calls, 2); assert.equal(result.output.diagnostics.degraded, true); });
test("Research Brain degrades deterministically on model failure", async () => { const result = await runResearchBrain(input, async () => { throw new Error("timeout"); }); assert.equal(result.output.diagnostics.degraded, true); assert.match(result.output.diagnostics.degradation_reasons[0], /timeout/); assert.equal(result.output.stock_radar.length, 0); });
