// @ts-nocheck
"use client";
type MacroObservation={series_key:string;series_name:string;agency:string;observation_date:string;value:number;mom_change:number|null;yoy_change:number|null;unit:string;source_url:string;is_preliminary:boolean};
const order=["cpi_all","cpi_core","ppi_final_demand"];
const names={cpi_all:"Headline CPI",cpi_core:"Core CPI",ppi_final_demand:"Final-demand PPI"};
function groups(rows){const map=new Map();rows.forEach((x)=>{if(!map.has(x.series_key))map.set(x.series_key,[]);map.get(x.series_key).push(x)});map.forEach((v)=>v.sort((a,b)=>new Date(a.observation_date)-new Date(b.observation_date)));return order.map((k)=>[k,map.get(k)||[]]).filter(([,v])=>v.length)}
function path(rows,w,h){const vals=rows.map((x)=>Number(x.value));const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,.001);return rows.map((x,i)=>`${i?"L":"M"}${(i/(Math.max(rows.length-1,1))*w).toFixed(2)},${(h-((Number(x.value)-min)/span)*h).toFixed(2)}`).join(" ")}
function pct(v){if(v===null||v===undefined||Number.isNaN(Number(v)))return"—";const n=Number(v);return`${n>0?"+":""}${n.toFixed(1)}%`}
export default function MacroSeriesCharts({observations=[],compact=false,title="Official government data",limit=3}:{observations?:MacroObservation[];compact?:boolean;title?:string;limit?:number}){const sets=groups(observations).slice(0,limit);if(!sets.length)return null;const w=compact?300:420,h=compact?88:126;return <section className={`macro-series-section ${compact?"compact":""}`}><header><div><span>BLS SERIES</span><h2>{title}</h2></div><p>Official monthly index history. Month-on-month and year-on-year rates are calculated from the stored BLS observations.</p></header><div className="macro-series-grid">{sets.map(([key,all])=>{const rows=all.slice(compact?-18:-24),latest=rows.at(-1),vals=rows.map((x)=>Number(x.value)),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,.001),lastY=h-((Number(latest.value)-min)/span)*h;return <article className="macro-series-card" key={key}><header><div><small>{latest.agency}</small><h3>{names[key]||latest.series_name}</h3></div><b>{pct(latest.yoy_change)}<small>y/y</small></b></header><svg viewBox={`0 0 ${w} ${h+18}`} role="img" aria-label={`${names[key]||key} trend`}><line x1="0" y1={h} x2={w} y2={h} className="macro-axis"/><path d={path(rows,w,h)} className="macro-line"/><circle cx={w} cy={lastY} r="4" className="macro-last-dot"/></svg><div className="macro-series-stats"><span><small>LATEST</small><b>{Number(latest.value).toFixed(3)}</b></span><span><small>M/M</small><b>{pct(latest.mom_change)}</b></span><span><small>PERIOD</small><b>{new Date(latest.observation_date).toLocaleDateString("en-GB",{month:"short",year:"numeric"})}</b></span></div><footer><span>{latest.is_preliminary?"Preliminary · subject to revision":latest.unit}</span><a href={latest.source_url} target="_blank" rel="noreferrer">BLS series ↗</a></footer></article>})}</div></section>}
