// @ts-nocheck
"use client";
type StoryLike={slug?:string;title?:string};type MacroObservation={series_key:string;observation_date:string;value:number;mom_change:number|null;yoy_change:number|null};type MarketObservation={series_key:string;observation_date:string;close:number};
const labels={cpi_all:"Headline CPI y/y",cpi_core:"Core CPI y/y",ppi_final_demand:"PPI final demand y/y",qqq:"QQQ monthly return",spy:"SPY monthly return",gld:"GLD monthly return",uup:"UUP monthly return",tlt:"TLT monthly return",uso:"USO monthly return",usdjpy:"USD/JPY monthly return",us2y:"US 2Y monthly change",us10y:"US 10Y monthly change"};
function pairFor(story){const text=`${story?.slug||""} ${story?.title||""}`.toLowerCase();if(/oil|iran|hormuz/.test(text))return["ppi_final_demand","uso","positive"];if(/yen|jpy/.test(text))return["us10y","usdjpy","positive"];if(/ai|chip|semi|earnings|mag7|china/.test(text))return["us10y","qqq","inverse"];if(/fed|rate|yield|debt|fiscal/.test(text))return["us2y","qqq","inverse"];if(/breadth/.test(text))return["us10y","spy","inverse"];return["us10y","spy","inverse"]}
function monthly(key,macro,market){const m=macro.filter((x)=>x.series_key===key).sort((a,b)=>new Date(a.observation_date)-new Date(b.observation_date));if(m.length)return m.map((x)=>({month:x.observation_date.slice(0,7),value:x.yoy_change??x.mom_change??Number(x.value)})).filter((x)=>x.value!==null);const rows=market.filter((x)=>x.series_key===key).sort((a,b)=>new Date(a.observation_date)-new Date(b.observation_date));return rows.map((x,i)=>{if(!i)return null;const prev=Number(rows[i-1].close),now=Number(x.close),value=/us2y|us10y/.test(key)?now-prev:((now/prev)-1)*100;return{month:x.observation_date.slice(0,7),value}}).filter(Boolean)}
function corr(a,b){if(a.length<4)return null;const ma=a.reduce((s,x)=>s+x,0)/a.length,mb=b.reduce((s,x)=>s+x,0)/b.length;let num=0,da=0,db=0;a.forEach((x,i)=>{const ax=x-ma,bx=b[i]-mb;num+=ax*bx;da+=ax*ax;db+=bx*bx});return da&&db?num/Math.sqrt(da*db):null}
function z(values){const mean=values.reduce((s,x)=>s+x,0)/values.length;const sd=Math.sqrt(values.reduce((s,x)=>s+Math.pow(x-mean,2),0)/Math.max(values.length-1,1))||1;return values.map((x)=>(x-mean)/sd)}
function svgPath(vals,w,h){const min=-2.5,max=2.5;return vals.map((v,i)=>`${i?"L":"M"}${(i/Math.max(vals.length-1,1)*w).toFixed(2)},${(h-((Math.max(min,Math.min(max,v))-min)/(max-min))*h).toFixed(2)}`).join(" ")}
export default function RelationshipChart({story,macroObservations=[],marketObservations=[],seriesKeys,title="Price relationship lens",compact=false}:{story?:StoryLike;macroObservations?:MacroObservation[];marketObservations?:MarketObservation[];seriesKeys?:string[];title?:string;compact?:boolean}){let[k1,k2,expected]=pairFor(story);const valid=(seriesKeys||[]).filter((k)=>macroObservations.some((x)=>x.series_key===k)||marketObservations.some((x)=>x.series_key===k));if(valid.length>=2){k1=valid[0];k2=valid[1]}const a=monthly(k1,macroObservations,marketObservations),b=monthly(k2,macroObservations,marketObservations),bm=new Map(b.map((x)=>[x.month,x.value])),aligned=a.filter((x)=>bm.has(x.month)).slice(compact?-16:-24),av=aligned.map((x)=>Number(x.value)),bv=aligned.map((x)=>Number(bm.get(x.month))),r=corr(av,bv);if(aligned.length<4)return <div className="relationship-empty">Relationship data is still being assembled for this story.</div>;const az=z(av),bz=z(bv),w=compact?320:520,h=compact?96:132;return <section className={`relationship-chart ${compact?"compact":""}`}><header><div><span>PRICE + CORRELATION</span><h3>{title}</h3></div><b className={r!==null&&r<0?"inverse":"positive"}>{r===null?"—":`r ${r.toFixed(2)}`}</b></header><p>{labels[k1]||k1} versus {labels[k2]||k2}. The expected relationship is <strong>{expected}</strong>, but the observed correlation is descriptive, regime-dependent and not proof of causation.</p><svg viewBox={`0 0 ${w} ${h+18}`} role="img" aria-label={`${labels[k1]} versus ${labels[k2]}`}><line x1="0" y1={h/2} x2={w} y2={h/2} className="relationship-zero"/><path d={svgPath(az,w,h)} className="relationship-line primary"/><path d={svgPath(bz,w,h)} className="relationship-line secondary"/></svg><footer><span><i className="primary"></i>{labels[k1]||k1}</span><span><i className="secondary"></i>{labels[k2]||k2}</span><small>{aligned.length} monthly observations</small></footer></section>}
